eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://trial-1009483.okta.com/oauth2/ausfki4vburm3ODSk697
    audience: api://microservice
